### ISSUE TITLE
New design proposal for the layout

### ISSUE THREAD

**Issue by devfake** [cybercog/laravel-paket#25]
Nice little package! Love it so far :)

But we could improve the layout a bit. It always works better when the design is more coherent.

I have roughly prepared a draft for the dashboard and the simple requirements page. Tell me what you think about it :)

I would agree to make the implementation in Vue, if you want. But would rather do it on the side, so it might take a while for me.

![dashboard](https://i.imgur.com/dO6bhIn.jpg)

![requirements](https://i.imgur.com/4v2wGot.jpg)

**Comment by antonkomarev** [comment]
@devfake thanks for that mockups!
Yeah, current interface is pretty clumsy and need to be reworked. PRs are always welcomed!

Couple of thoughts to consider:
1. I was wanted to move top menu to the left and [make it looks like Telescope](https://camo.githubusercontent.com/bbacae2220454ed7c5fd94106976d4ba4bec058b/68747470733a2f2f7265732e636c6f7564696e6172792e636f6d2f6474666276766b79702f696d6167652f75706c6f61642f76313533393131303836302f53637265656e5f53686f745f323031382d31302d30395f61745f312e34372e32335f504d2e706e67).
2. We need to think what should be displayed on Dashboard to make it more useful (maybe analysis of possible packages updates, deprecation warnings, etc).
3. I was wanted to make list of requirements filterable
4. Need to think about Dependencies list inside of the Requirements (they are taking too much space)
5. Package could have more than one license (I've just displayed only 1 per package for now)
6. Package layout in 2 columns looks good, but I don't like new line breaks in names (maybe it will be better to split `vendor/package-name` and write them separately?
7. It will be super awesome to use Tailwind CSS instead of Bootstrap.

**Comment by devfake** [comment]
Hey, no problem :)

I think it would make sense to do it like Telescope. This would resolve some of your points directly (better view with a list, space problems, filters and more).

Is it allowed for you to use the layout (with code) of Telescope? I don't know if this is allowed, even if it's open source. Because then it would be easy to change the layout :)

**Comment by antonkomarev** [comment]
Telescope is MIT licensed, that means we can easily take parts from it. The only one thing I don't like - Telescope is using Bootstrap :\ It's not that bad, but Tailwind CSS seems very promising and as far as I know new secret project from Taylor will use it too and I suppose it's just a matter of time to migrate Telescope to Tailwind.

**Comment by devfake** [comment]
This looks like a great task for someone who wants to start with open source (or want to learn Tailwind). Possibly you could post this project in "open source help wanted" lists :)

**Comment by antonkomarev** [comment]
Tailwind is not strict requirement, it's just a preference. We could keep Bootstrap implementation and refactor it later. At this stage design revision is more important than exact implementation.

**Comment by antonkomarev** [comment]
New design was shipped in v1.2.0
